// Script to add sample tracks to MongoDB
const tracks = [
  {
    trackId: 'battle-001',
    title: 'Epic Battle Theme',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 240,
    category: 'battle',
    description: 'An epic battle theme for intense combat scenes',
    instruments: ['drums', 'guzheng', 'erhu'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'battle-002',
    title: 'Warrior\'s Call',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 200,
    category: 'battle',
    description: 'A powerful theme for warrior battles',
    instruments: ['drums', 'trumpet', 'strings'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'story-001',
    title: 'Story Theme',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 180,
    category: 'story',
    description: 'A narrative theme for storytelling moments',
    instruments: ['piano', 'violin'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'story-002',
    title: 'Tale of Legends',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 220,
    category: 'story',
    description: 'A legendary tale theme',
    instruments: ['flute', 'harp', 'strings'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'exploration-001',
    title: 'Exploration Theme',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 190,
    category: 'exploration',
    description: 'An adventure theme for exploration',
    instruments: ['flute', 'guzheng', 'bamboo'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'exploration-002',
    title: 'Journey Begins',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 210,
    category: 'exploration',
    description: 'The beginning of an epic journey',
    instruments: ['pipa', 'erhu', 'drums'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'emotional-001',
    title: 'Emotional Theme',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 195,
    category: 'emotional',
    description: 'A touching emotional piece',
    instruments: ['erhu', 'piano', 'strings'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'ambient-001',
    title: 'Ambient Theme',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 300,
    category: 'ambient',
    description: 'A peaceful ambient background',
    instruments: ['guzheng', 'flute', 'nature sounds'],
    isHidden: false,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  },
  {
    trackId: 'hidden-001',
    title: 'Hidden Treasure',
    artist: 'PBZ Music',
    youtubeUrl: 'https://www.youtube.com/watch?v=DSY7u8Jg9c0',
    duration: 250,
    category: 'hidden',
    description: 'An exclusive hidden track for true fans',
    instruments: ['all instruments'],
    isHidden: true,
    playCount: 0,
    monthlyPlayCount: 0,
    upvotes: 0,
    monthlyUpvotes: 0,
    pinCount: 0,
    monthlyPinCount: 0,
    upvotedBy: []
  }
];

// Print tracks as MongoDB insertMany command
console.log('db.tracks.insertMany(');
console.log(JSON.stringify(tracks, null, 2));
console.log(');');
